### ISSUE TITLE
Should/could this library be used for the pub/sub type of work?

### ISSUE THREAD

**Issue by patefacio** [luca3m/redis3m#15]
If so are there any examples or snippets available?

**Comment by patefacio** [comment]
I'm not sure if that works - at least it is not obvious. The use case is a server that uses redis pub for communication as well as database. Currently using redisclient which has boost asio incorporated to get the ansync nature going. I have two issues with it which is why I'm trying to see if redis3m will work better. The first is I'm not sure how in that setup to make something asynchronous to be synchronous when needed. The second is I'm seeing bogus data when thousands of publish messages go through (similar to this guy's issue https://github.com/nekipelov/redisclient/issues/4). I think your approach to handling the data is different/preferred as it looks like you don't implement parsing but rely on hiredis which I imagine is well tested. But what I don't see in your approach is how to subscribe to say 10 message topics in a server loop (i.e. what the asio in the other package nicely provides). [Here is my use case](https://github.com/patefacio/RedisExchange/blob/master/exch/cpp/app/exch_server/exch_server.cpp)

What are thoughts/suggestions?

**Comment by luca3m** [comment]
If you use Redis as database and to subscribe, you have to use two separate connections. The first usually use synchronous operations, the second may need an event based approach.

Redis3m is perfect for the former, for the second you have to implement an eventloop yourself, like I did with the `while(true)`. Performance may be worse than a boost:asio based one. You should not have the bug mentioned because the network layer is well tested and managed by hiredis library.

**Comment by patefacio** [comment]
Thank you. I ended up using just straight hiredis with their libuv adaptor since there was example code and it is working fine.

**Comment by nidhijha** [comment]
I tried using the above code you showed for subscribe but it seems loop is blocked while waiting for response. I just tried printing some value in the start of loop and it won't print anything.

Also can you give example of how to subscribe to multiple events from single process?

**Comment by luca3m** [comment]
@nidhijha the subscriber is correct that is blocked waiting for messages. On each loop iteration it will handle a received message. Now you can find this code on [examples](https://github.com/luca3m/redis3m/tree/master/examples) too.

According to [SUBSCRIBE](http://redis.io/commands/subscribe) command reference, you have simply to add multiple channels when you call it:

```
conn->run(command("SUBSCRIBE") << "topic" << "topic2" << "topic3");
```
