### ISSUE TITLE
How to implement lock using redis3m. 

### ISSUE THREAD

**Issue by nidhijha** [luca3m/redis3m#18]
Lets say my use case is, There are 2 processes trying to acquire lock on some key. One of them succeed, while other will just wait. Once first one is done updating the value it should release lock and then 2nd process can acquire lock if want or use the value updated by 1st one. I am talking about similar methods from StackExchange.Redis for c#
1. LockTake
2. LockRelease
3. LockExtend
4. LockQuery

**Comment by luca3m** [comment]
Lock are implemented in Redis using [SET](http://redis.io/commands/set) command and its options. StackExchange.Redis does the same as I can see on their code. So you issue these commands using redis3m too, for example the lockTake should look in this way:

```C++
using namespace redis3m;
connection::ptr_t conn = connection::create();
conn->run(command("SET") << "lockname" << "EX" << expiretime << "NX");
// if response is OK you have got the lock, otherwise you don't have it
```

I called these common features *patterns*. You can find some [here](https://github.com/luca3m/redis3m/tree/master/include/redis3m/patterns), they are included on redis3m. If you want you can create a new one for locks and we can include it on redis3m.

**Comment by nidhijha** [comment]
Thanks, I have implemented lock using SET, MULTI, EXEC ,WATCH commands.

**Comment by luca3m** [comment]
Cool! :)
