### ISSUE TITLE
Is redis3m thread safe?

### ISSUE THREAD

**Issue by typcn** [luca3m/redis3m#23]
I want to use redis3m in my web service , is it thread safe ?

**Comment by luca3m** [comment]
Hi,

Yes it is. You can share `simple_pool` or `connection_pool` classes between threads and get a usable connection object when each thread needs to use a connection. The former is useful when you have a single redis instance, the latter if you have master/slaves managed by sentinels. Follow examples [here](https://github.com/luca3m/redis3m/blob/master/examples/simple_pool.cpp) and [here](https://github.com/luca3m/redis3m/blob/master/examples/ha_pool.cpp), if you have other questions ask here. Using C++11 lambdas, there are convenient methods to auto-retry you database related code if connection fails.

**Comment by typcn** [comment]
OK , Thanks for response.
