### ISSUE TITLE
Connection with UNIX sockets

### ISSUE THREAD

**Issue by chaseholland** [luca3m/redis3m#24]
Is is possible to create connections using unix sockets for local redis connections as suggested by http://redis.io/topics/latency?

**Comment by luca3m** [comment]
Hi,

Yes it's possible but we need to modify `redis3m::connection` A new constructor should be made which uses `redisContext *redisConnectUnix(const char *path);` of hiredis. Do you like to take care of it? Otherwise I'll do it when I have some time.

Thanks,
Luca

**Comment by jamesmarlowe** [comment]
Is https://github.com/luca3m/redis3m/pull/33 what you had in mind for this?
