### ISSUE TITLE
Why not establish multiple connections with Master/Slave?

### ISSUE THREAD

**Issue by xiaotaoz** [luca3m/redis3m#29]
In APIs create_slave_connection() and create_master_connection(), they will return directly after establishing only one connection, so we have at most 2 connections available any time.

Why not make the connection to all Masters & Slaves, then redis3m users have more connections available, which might be better for load sharing.

**Comment by luca3m** [comment]
Hi,

We have already a pool of connections, look at [connection_pool::get](https://github.com/luca3m/redis3m/blob/master/src/connection_pool.cpp#L47) and [connection_pool::put](https://github.com/luca3m/redis3m/blob/master/src/connection_pool.cpp#L110). The former creates a new connection there isn't already one available of that type, the latter puts a connection back to the pool for reuse.

There is also an [example](https://github.com/luca3m/redis3m/blob/master/examples/ha_pool.cpp), does it make sense?

**Comment by xiaotaoz** [comment]
Thanks for your quick reply!

If there's existing connection for Master/Slave/Any, connection_pool::get() will return without creating new ones. So we only can have 1 connection for Master and 1 for Slave.

Is it possible to have multiple connections for Master or Slave.

**Comment by luca3m** [comment]
It will create a new one if there are not any available inside the pool. When connections are used by threads their are not inside the pool. So if you have multiple threads getting connections, it will create multiple connections as they are needed.

**Comment by xiaotaoz** [comment]
OK.
Then for one thread, only one connection is supported now.
Do you have plan to support multiple connections in one thread?

**Comment by luca3m** [comment]
I don't understand very well your use case. Why you need more connections on a single thread? A single thread can do one thing at time, so if it's executing a command, it can execute anything else.

**Comment by xiaotaoz** [comment]
Yes. The purpose here is to use multiple connections instead of one connection for all queries, in order to prevent ‘head-of the line’ delay, and potential bandwidth issues in case that the responses are large (supposedly many transactions and/or large transaction responses can cause issues), even if we're in one thread.

**Comment by luca3m** [comment]
Why you not use [pipelines](http://redis.io/topics/pipelining)? You can use `connection::append` to send a command and separately `connection::get_reply` to read an answer. So you can send a bunch of commands and after read all replies together, using a single connection.

**Comment by xiaotaoz** [comment]
OK, Thanks for your info!
