### ISSUE TITLE
Can sentinels have different ports?

### ISSUE THREAD

**Issue by GrossoMoreira** [luca3m/redis3m#52]
I'm looking at the connection_pool::create() function that receives a list of sentinel hostnames separated by commas. But then it seems that the port number has to be the same for all sentinels. Is there a way to specify different port numbers for each sentinel?

Thank you!

**Comment by luca3m** [comment]
Theoretically you can, but current API exposed by redis3m does not allow to specify multiple ports.

Usually I think it's better to use the same port. But if you really need you can try to patch redis3m, the code should be feasible to tweak.

**Comment by GrossoMoreira** [comment]
Ok, thanks!
